
# The scene_id and scene_data for the NZW30 are as follows:
# 
# Action            scene_id     scene_data
# Double tap down      1             3
# Triple tap down      1             4
# Quad tap down        1             5
# Five tap down        1             6
# Long hold down       1             1
# 
# Double tap up        2             3
# Triple tap up        2             4
# Quad tap up          2             5
# Five tap up          2             6
# Long hold up         2             1

# Hank
#
# Action         Pictogram         scene_id     scene_data
# Button one tap     Moon and Star         1         0
# Button one hold     Moon and Star         1         2
# Button one release     Moon and Star         1         1
# Button two tap     People             2         0
# Button two hold     People             2         2
# Button two release     People             2         1
# Button three tap     Circle             3         0
# Button three hold     Circle             3         2
# Button three release     Circle             3         1
# Button four tap     Circle with Line     4         0
# Button four hold     Circle with Line     4         2
# Button four release     Circle with Line     4         1


#- alias: "Living room lights on"
#  trigger:
#    platform: event
#    event_type: zwave.scene_activated
#    event_data:
#      entity_id: zwave.switch_livingroom_light
#      scene_id: 2 # double tap up
#      scene_data: 3
#  action:
#    service: scene.turn_on
#    entity_id: scene.livingroom_lights_on
    
- alias: "Livingroom lights on"
  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_livingroom_light
      scene_id: 2 # up
      scene_data: 0 # tap
  action:
    service: script.turn_on
    entity_id: script.livingroom_normal
    
- alias: "Livingroom lights off"
  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_livingroom_light
      scene_id: 1 # down
      scene_data: 0 # tap
  action:
    service: light.turn_off
    entity_id: light.livingroom
    
- alias: "Livingroom lights full"
  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_livingroom_light
      scene_id: 2 # up
      scene_data: 3 # double-tap
  action:
    service: script.turn_on
    entity_id: script.livingroom_bright

- alias: "Livingroom lights dim"
  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_livingroom_light
      scene_id: 1 # down
      scene_data: 3 # double-tap
  action:
    service: script.turn_on
    entity_id: script.livingroom_dim
    
- alias: "Office lights on"
  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_office
      scene_id: 2 # up
      scene_data: 0 # tap
  action:
    service: light.turn_on
    entity_id: light.office

- alias: "Office lights off"
  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_office
      scene_id: 1 # down
      scene_data: 0 # tap
  action:
    service: light.turn_off
    entity_id: light.office

- alias: "Basement lights off"
  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_basement
      scene_id: 1 # down
      scene_data: 0 # tap
  action:
    service: light.turn_off
    entity_id: light.basement

- alias: "Basement lights on"
  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_basement
      scene_id: 2 # up
      scene_data: 0 # tap
  action:
    service: light.turn_on
    entity_id: light.basement

- alias: "Movie start"
  hide_entity: true
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.switch_basement
        scene_id: 1 # down
        scene_data: 3 # double-tap
    - platform: state
      entity_id: media_player.room1_main
      from: 'off'
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.movie

- alias: "Movie end"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: media_player.room1_main
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_on
      entity_id: light.basement

- alias: "Vacation - turn on lights at sunset"
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.vacation
      state: "on"
  action:
    - service: script.turn_on
      entity_id: script.livingroom_normal

- alias: "Vacation - bedroom lights on"
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation
      state: "on"
  action:
    - service: script.turn_on
      entity_id: script.bedroom_normal

- alias: "Vacation - go to bed"
  trigger:
    - platform: time
      at: '00:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_dim
    - service: light.turn_off
      entity_id: light.livingroom
