- alias: Vacation - turn on lights at sunset
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.livingroom_normal
  id: 09605e8de26c4f15981dc9a2f18eb911
- alias: Vacation - bedroom lights on
  initial_state: true
  trigger:
  - platform: time
    at: '21:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.bedroom_normal
  id: 42c526154916467cb504b76f32b3d98d
- alias: Vacation - go to bed
  initial_state: true
  trigger:
  - platform: time
    at: 00:00:00
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.bedroom_dim
  - service: light.turn_off
    entity_id: light.livingroom
  id: 75710f9b4ca14810a204aacac85ef917
- alias: Update Available Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
  - service: notify.notify
    data_template:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} is available.
  id: e30a51aa1e2240f7be81b28514d1369d
- alias: Garage Door Open Set Switch Color
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_tilt_sensor
    to: 'on'
  action:
  - service: script.zwave_inovelli_led_color
    data:
      nodeid: 23
      color: red
      duration: 'on'
      effect: pulse
      level: 100
  id: 43d5c2acebdf4ac4a3f9bcf97d37aeb8
- alias: Garage Door Close Set Switch Color
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_tilt_sensor
    to: 'off'
  action:
  - service: script.zwave_inovelli_led_color
    data:
      nodeid: 23
      duration: 'off'
      effect: 'off'
  id: d6be07ceb58846378d06f62bc7eca64b
- alias: Media start
  initial_state: true
  trigger:
  - platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 2
      scene_id: 1
      scene_value_label: Pressed 2 Times
  action:
  - service: script.media_start
  id: 27581524d1b34a83a9bd3991c631ece7
- alias: Media pause
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.basement_receiver_main
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: light.basement
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.media_pause
  id: 72424910e5ac43e4af4d2e7779a562da
- alias: Bathroom fan 10 minutes
  initial_state: true
  trigger:
  - platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 29
      scene_id: 2
      scene_value_label: Pressed 2 Times
  action:
  - service: switch.turn_on
    entity_id: switch.upstairs_bathroom_fan_switch
  - delay: 00:10:00
  - service: switch.turn_off
    entity_id: switch.upstairs_bathroom_fan_switch
  id: 718ff1064dbb462ca75d1df463389fe7
- alias: Bathroom fan 20 minutes
  initial_state: true
  trigger:
  - platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 29
      scene_id: 2
      scene_value_label: Pressed 3 Times
  action:
  - service: switch.turn_on
    entity_id: switch.upstairs_bathroom_fan_switch
  - delay: 00:20:00
  - service: switch.turn_off
    entity_id: switch.upstairs_bathroom_fan_switch
  id: 68efc2ae12fe4513837f4abc39772660
- id: '1592672504537'
  alias: Notify T-1000 bin full
  description: ''
  trigger:
  - device_id: 2a15b8b3c35c44009c84069f867f8583
    domain: binary_sensor
    entity_id: binary_sensor.t_1000_bin_full
    platform: device
    type: turned_on
  condition: []
  action:
  - data:
      message: Please empty T-1000 bin
      title: T-1000 Roomba bin is full
    service: notify.notify
- id: '1592672552040'
  alias: New Automation
  description: ''
  trigger:
  - device_id: 73fef5d5e8d945a695a863fbd51cdecc
    domain: binary_sensor
    entity_id: binary_sensor.hal_bin_full
    platform: device
    type: turned_on
  condition: []
  action:
  - data:
      message: Please empty Hal bin
      title: Hal Roomba bin is full
    service: notify.notify
- id: '1592677647678'
  alias: Clean on Sunday morning
  description: ''
  trigger:
  - at: '9:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - device_id: 2a15b8b3c35c44009c84069f867f8583
    domain: vacuum
    entity_id: vacuum.t_1000
    type: clean
