homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.065345
  longitude: -89.520864
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 230
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: UTC
  # Customization file
  customize_glob:
    "zwave.unknown_node_2*":
      hidden: true
    "sensor.vision_zd2102_eu_doorwindow_sensor_*":
      hidden: true
    "light.livingroom_fixture_*":
      hidden: true
    "light.bedroom_*":
      hidden: true

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

zwave:
  config_path: /home/homeassistant/open-zwave/config
  usb_path: /dev/ttyACM0

lifx:
  
light:
  - platform: group
    name: Livingroom Fixture
    entities:
      - light.livingroom_fixture_1
      - light.livingroom_fixture_2
      - light.livingroom_fixture_3
  - platform: group
    name: Bedroom
    entities:
      - light.bedroom_1
      - light.bedroom_2

media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.68
  - platform: panasonic_viera
    host: 192.168.1.71

scene:
  - name: Livingroom Lights On
    entities:
      light.livingroom_rgb:
        state: on
        brightness: 255
      light.livingroom_fixture:
        state: on
        brightness: 255
      switch.livingroom_light:
        state: on
  - name: Livingroom Lights Off
    entities:
      light.livingroom_rgb:
        state: off
      light.livingroom_fixture:
        state: off
      switch.livingroom_light:
        state: off
  - name: Livingroom Lights Half
    entities:
      light.livingroom_rgb:
        state: on
        brightness: 127
      light.livingroom_fixture:
        state: on
        brightness: 127
      switch.livingroom_light:
        state: on
  - name: Bedroom Lights Off
    entities:
      light.bedroom:
        state: off
  - name: Bedroom Lights On
    entities:
      light.bedroom:
        state: on
        brightness: 127
  - name: Go to sleep
    entities:
      scene.bedroom_lights_off:
        state: on
      scene.livingroom_lights_off:
        state: on


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

