homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  time_zone: !secret time_zone
  # Customization file
  auth_mfa_modules:
    - type: totp
  customize:
    binary_sensor.garage_tilt_sensor:
      device_class: door

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    icon: mdi:home

  - name: XES
    latitude: !secret xes_latitude
    longitude: !secret xes_longitude
    radius: 250
    icon: mdi:briefcase

system_health:
updater:
  reporting: false
  include_used_components: false

hacs:
  token: 30274465c1f41b33693813753c3307edc2bd57f2

recorder:
  db_url: postgresql://@/ha
  purge_keep_days: 30
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light
      - media_player
      - device_tracker
      - person
      - zwave

history:
history_graph:
  lights:
    hours_to_show: 120
    entities:
      - light.livingroom
      - light.kitchen
      - light.basement
      - light.bedroom
      - light.front_door


sensor:
  - platform: template
    sensors:
      # Batteries
      front_door_battery:
        entity_id: zwave.front_door_lock
        value_template: "{{ states.zwave.front_door_lock.attributes.battery_level }}"
        friendly_name: 'Front Door Lock Battery'
        unit_of_measurement: '%'
      garage_door_battery:
        entity_id: zwave.garage_door_lock
        value_template: "{{ states.zwave.garage_door_lock.attributes.battery_level }}"
        friendly_name: 'Garage Door Lock Battery'
        unit_of_measurement: '%'
      basement_smoke_alarm_battery:
        entity_id: zwave.basement_fire_alarm
        friendly_name: 'Downstairs Smoke Alarm Battery'
        value_template: '{{ states.zwave.basement_fire_alarm.attributes.battery_level }}'
        icon_template: 'mdi:battery-outline'
        unit_of_measurement: '%'
      garage_tilt_sensor_battery:
        entity_id: zwave.garage_door_tilt_sensor
        friendly_name: 'Garage Tilt Sensor Battery'
        value_template: '{{ states.zwave.garage_door_tilt_sensor.attributes.battery_level }}'
        icon_template: 'mdi:battery-outline'
        unit_of_measurement: '%'
      bedroom_keypad_0_battery:
        entity_id: zwave.button_bedroom_0
        friendly_name: 'Bedroom Keypad 0 Battery'
        value_template: '{{ states.zwave.button_bedroom_0.attributes.battery_level }}'
        icon_template: 'mdi:battery-outline'
        unit_of_measurement: '%'
      bedroom_keypad_1_battery:
        entity_id: zwave.button_bedroom_1
        friendly_name: 'Bedroom Keypad 1 Battery'
        value_template: '{{ states.zwave.button_bedroom_1.attributes.battery_level }}'
        icon_template: 'mdi:battery-outline'
        unit_of_measurement: '%'
      bedroom_door_sensor_battery:
        entity_id: zwave.bedroom_sliding_door_sensor
        friendly_name: 'Bedroom Door Sensor Battery'
        value_template: '{{ states.zwave.bedroom_sliding_door_sensor.attributes.battery_level }}'
        icon_template: 'mdi:battery-outline'
        unit_of_measurement: '%'

      basement_smoke_alarm_status:
        friendly_name: 'Downstairs Smoke Alarm Status'
        value_template: >-
          {% if is_state("sensor.basement_fire_alarm_level", "255") and is_state("sensor.basement_fire_alarm_type", "1") %}
            smoke
          {% elif is_state("sensor.basement_fire_alarm_level", "255") and is_state("sensor.basement_fire_alarm_type", "2") %}
            carbon monoxide
          {% else %}
            idle
          {% endif %}
        icon_template: >-
          {% if is_state("sensor.basement_fire_alarm_level", "255") and is_state("sensor.basement_fire_alarm_type", "1") %}
            mdi:fire
          {% elif is_state("sensor.basement_fire_alarm_level", "255") and is_state("sensor.basement_fire_alarm_type", "2") %}
            mdi:cloud-outline
          {% else %}
            mdi:smoke-detector
          {% endif %}

binary_sensor:
  - platform: template
    sensors:
      bedroom_door_open:
        device_class: door
        value_template: "{{ is_state('sensor.bedroom_door_alarm_level', '255') }}"
        friendly_name: 'Bedroom Door'


http:
  server_host: 127.0.0.1
  base_url: https://ha.jkhome.network
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

frontend:
lovelace:

mobile_app:
device_tracker:
person:
map:


config:
logger:
  default: info
#  logs:
#    homeassistant.components.lifx.light: debug
sun:

zwave:
  #config_path: /srv/homeassistant/config/open-zwave/config
  usb_path: /dev/ttyACM0
  autoheal: false
  polling_interval: 30000

lifx:
  light:
    server: 10.52.100.11

light:
  - platform: switch
    name: Livingroom Switch
    entity_id: switch.livingroom_light
  - platform: group
    name: Livingroom Fixture
    entities:
      - light.livingroom_fixture_1
      - light.livingroom_fixture_2
      - light.livingroom_fixture_3
  - platform: group
    name: Livingroom
    entities:
      - light.livingroom_switch
      - light.livingroom_fixture
      - light.livingroom_entry_table
  - platform: group
    name: Bedroom
    entities:
      - light.bedroom_1
      - light.bedroom_2
  - platform: group
    name: Basement
    entities:
      - light.basement_overhead
      - light.basement_lamp
  - platform: switch
    name: Office Right Fixture
    entity_id: switch.plug_office_ch0
  - platform: switch
    name: Office Left Fixture
    entity_id: switch.plug_office_ch1
  - platform: group
    name: Office
    entities:
      - light.office_right_fixture
      - light.office_left_fixture

switch:
  - platform: flux
    name: Bedroom Flux
    lights:
      - light.bedroom
    start_time: '7:00'
    stop_time: '22:00'
    start_colortemp: 2700
    stop_colortemp: 2200
    sunset_colortemp: 2500
    mode: mired
    transition: 1
    interval: 120
    brightness: 150
  - platform: flux
    name: Livingroom Flux
    lights:
      - light.livingroom
    start_time: '7:00'
    stop_time: '22:00'
    start_colortemp: 2700
    stop_colortemp: 2000
    sunset_colortemp: 2200
    mode: mired
    transition: 1
    interval: 120
    brightness: 150



media_player:
  - platform: yamaha_musiccast
    host: 10.52.110.12
    port: 5005
  - platform: yamaha_musiccast
    host: 10.52.110.14
    port: 5006
  - platform: panasonic_viera
    host: 10.52.110.10
    mac: c0:d9:62:ae:17:1a
    name: "Basement TV"
  - platform: snapcast
    host: 192.168.1.40
  #- platform: mpd
  #  host: 192.168.1.99
  #- name: Jordan Spotify
  #  platform: spotify
  #  client_id: ec374d9d19c848949af1af9f588a0871
  #  client_secret: 2566509f7a6e426dbf3e21081d872f3d
  #  cache_path: /srv/homeassistant/config/.spotify-token-cache-jordan
  #- name: Kristen Spotify
  #  platform: spotify
  #  client_id: a591978a38214a3cb6cc91f32a8731f4
  #  client_secret: 8425eeae132f41d18e10be24e3dd5f52
  #  cache_path: /srv/homeassistant/config/.spotify-token-cache-kristen

roku:
  - host: 10.52.110.13

script:
  livingroom_bright:
    alias: Livingroom Bright
    sequence:
      - service: switch.turn_off
        entity_id: switch.livingroom_flux
      - service: light.turn_on
        entity_id: light.livingroom
        data:
          transition: 1
          brightness_pct: 90
          kelvin: 2700
  livingroom_normal:
    alias: Livingroom Normal
    sequence:
      - service: light.turn_on
        entity_id: light.livingroom
      - service: switch.turn_on
        entity_id: switch.livingroom_flux
      - service: switch.livingroom_flux_update
        entity_id: switch.livingroom_flux
  livingroom_dim:
    alias: Livingroom Dim
    sequence:
      - service: switch.turn_off
        entity_id: switch.livingroom_flux
      - service: light.turn_on
        entity_id: light.livingroom
        data:
          transition: 1
          brightness_pct: 15
          kelvin: 2000
  media_start:
    alias: Media Play
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.basement
          transition: 2
          brightness: 25
  media_pause:
    alias: Media Pause
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.basement
          transition: 2
          brightness: 255

input_boolean:
  vacation:
    name: Vacation Mode
    initial: off
    icon: mdi:hotel


automation: !include automations.yaml
