homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: !secret time_zone
  # Customization file
  customize_glob:
    "zwave.unknown_node_2*":
      hidden: true
    "sensor.vision_zd2102_eu_doorwindow_sensor_*":
      hidden: true
    "light.livingroom_fixture_*":
      hidden: true
    "light.bedroom_*":
      hidden: true

frontend:
config:
logger:
  default: debug
sun:
sensor:
#  - platform: yr
  - platform: time_date
    display_options:
      - 'date_time'
      - 'time_utc'

zwave:
  config_path: /home/homeassistant/open-zwave/config
  usb_path: /dev/ttyACM0

lifx:
  
light:
  - platform: switch
    name: Livingroom Switch
    entity_id: switch.livingroom_light
  - platform: group
    name: Livingroom Fixture
    entities:
      - light.livingroom_fixture_1
      - light.livingroom_fixture_2
      - light.livingroom_fixture_3
  - platform: group
    name: Livingroom
    entities:
      - light.livingroom_switch
      - light.livingroom_fixture
      - light.livingroom_rgb
  - platform: group
    name: Bedroom
    entities:
      - light.bedroom_1
      - light.bedroom_2
  - platform: switch
    name: Basement Switch
    entity_id: switch.basement
  - platform: switch
    name: Basement Lamp
    entity_id: switch.plug_basement_0
  - platform: switch
    name: Basement Switch
    entity_id: switch.basement
  - platform: group
    name: Basement
    entities:
      - light.basement_switch
      - light.basement_lamp
  - platform: switch
    name: Office Lamp
    entity_id: switch.plug_office_ch1
  - platform: group
    name: office
    entities:
      - light.office_lamp

switch:
  - platform: flux
    name: Bedroom Flux
    lights:
      - light.bedroom
    start_time: '7:00'
    stop_time: '22:00'
    start_colortemp: 2700
    stop_colortemp: 2200
    sunset_colortemp: 2500
    mode: mired
    transition: 1
    interval: 120
    brightness: 150
  - platform: flux
    name: Livingroom Flux
    lights:
      - light.livingroom
    start_time: '7:00'
    stop_time: '22:00'
    start_colortemp: 2700
    stop_colortemp: 2000
    sunset_colortemp: 2200
    mode: mired
    transition: 1
    interval: 120
    brightness: 150



media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.23
  - platform: panasonic_viera
    host: 192.168.1.21
    mac: c0:d9:62:ae:17:1a 
  - platform: snapcast
    host: 192.168.1.99
  - platform: mpd
    host: 192.168.1.99

scene:
  - name: Movie
    entities:
      light.basement_switch:
        state: off
      light.basement_lamp:
        state: on

script:
  livingroom_bright:
    alias: Livingroom Bright
    sequence:
      - service: switch.turn_off
        entity_id: switch.livingroom_flux
      - service: light.turn_on
        entity_id: light.livingroom
        data:
          transition: 1
          brightness_pct: 90
          kelvin: 2700
  livingroom_normal: 
    alias: Livingroom Normal
    sequence:
      - service: light.turn_on
        entity_id: light.livingroom
      - service: switch.turn_on
        entity_id: switch.livingroom_flux
      - service: switch.livingroom_flux_update
        entity_id: switch.livingroom_flux
  livingroom_dim:
    alias: Livingroom Dim
    sequence:
      - service: switch.turn_off
        entity_id: switch.livingroom_flux
      - service: light.turn_on
        entity_id: light.livingroom
        data:
          transition: 1
          brightness_pct: 15
          kelvin: 2000

input_boolean:
  vacation:
    name: Vacation Mode
    initial: off
    icon: mdi:hotel


group: !include groups.yaml
automation: !include automations.yaml

