media_player:
  - platform: wha
    name: home
    snapgroup: media_player.snapcast_group_71aecdd3_beac_781a_5e6b_f6e823e66f93
    sources:
      - name: "Spotify Jordan"
        snapcast_source: "Spotify_Jordan"
        entity_id: media_player.spotify_jordan
        select_source: "Snapcast"
      - name: "Spotify Kristen"
        snapcast_source: "Spotify_Kristen"
        entity_id: media_player.spotify_kristen
        select_source: "Snapcast"
      - name: "MPD"
        snapcast_source: "MPD"
        entity_id: media_player.mpd

    speakers:
      - name: livingroom
        on_default: false
        snapclient:
          entity_id: media_player.snapcast_client_livingroom
        receiver:
          entity_id: media_player.livingroom_receiver_main
          source: coaxial
          volume:
            min: 30
            max: 70
            default: 40
      - name: kitchen
        on_default: true
        snapclient:
          entity_id: media_player.snapcast_client_kitchen
          volume:
            min: 0
            max: 40
            default: 10
      - name: basement
        on_default: false
        snapclient:
          entity_id: media_player.snapcast_client_basement
        receiver:
          entity_id: media_player.dunno
          source: aux
          volume:
            min: 20
            max: 40
            default: 25

  - platform: yamaha_musiccast
    host: 10.52.110.12
    port: 5005

  - platform: yamaha_musiccast
    host: 10.52.110.14
    port: 5006

  - platform: snapcast
    host: 192.168.1.12

  - platform: mpd
    host: 192.168.1.12
    port: 6600



spotify:
  client_id: !secret jordan_spotify_client_id
  client_secret: !secret jordan_spotify_client_secret


automation:
#  - alias: "Audio play WPR"
#    trigger:
#      - platform: event
#        event_type: ozw.scene_activated
#        event_data:
#          entity_id: ozw.livingroom_button_controller
#          scene_id: 2 # people
#          scene_data: 0 # tap
#    action:
#      - service: media_player.turn_on
#        entity_id: media_player.home
#      - service: media_player.select_source
#        data:
#          entity_id: media_player.home
#          source: mpd
#      - service: media_player.play_media
#        entity_id: media_player.home
#        data:
#          media_content_id: "https://wpr-ice.streamguys1.com/wpr-ideas-mp3-64"
#          media_content_type: channel
#
#  - alias: "Audio play Kristen Spotify"
#    trigger:
#      platform: event
#      event_type: ozw.scene_activated
#      event_data:
#        entity_id: ozw.livingroom_button_controller
#        scene_id: 4 # circle with line
#        scene_data: 0 # tap
#    action:
#      - service: media_player.turn_on
#        entity_id: media_player.home
#      - service: media_player.select_source
#        data:
#          entity_id: media_player.home
#          source: Kristen Spotify
#
#  - alias: "Audio play Spotify Jordan"
#    trigger:
#      platform: event
#      event_type: ozw.scene_activated
#      event_data:
#        entity_id: ozw.livingroom_button_controller
#        scene_id: 1 # moon and star
#        scene_data: 0 # tap
#    action:
#      - service: media_player.turn_on
#        entity_id: media_player.home
#      - service: media_player.select_source
#        data:
#          entity_id: media_player.home
#          source: Spotify Jordan
