
# NZW3x
#
# Action            scene_id     scene_value_id
# Double tap down   1            3
# Triple tap down   1            4
# Quad tap down     1            5
# Five tap down     1            6
# Long hold down    1            1
#
# Double tap up     2            3
# Triple tap up     2            4
# Quad tap up       2            5
# Five tap up       2            6
# Long hold up      2            1

# LZW3x
#
# Button Press   Scene ID     Scene Data
# 1 x Up         2            7680
# 1 x Down       1            7680
# 2 x Up         2            7860
# 2 x Down       1            7860
# 3 x Up         2            7920
# 3 x Down       1            7920
# 4 x Up         2            7980
# 4 x Down       1            7980
# 5 x Up         2            8040
# 5 x Down       1            8040
# 1 x Config     3            7680
# Hold Up        2            7800
# Release Up     2            7740
# Hold Down      1            7800
# Release Down   1            7740

# Hank
#
# Action                Pictogram         scene_id     scene_value_id
# Button one tap        Moon and Star     1            0
# Button one hold       Moon and Star     1            2
# Button one release    Moon and Star     1            1
# Button two tap        People            2            0
# Button two hold       People            2            2
# Button two release    People            2            1
# Button three tap      Circle            3            0
# Button three hold     Circle            3            2
# Button three release  Circle            3            1
# Button four tap       Circle with Line  4            0
# Button four hold      Circle with Line  4            2
# Button four release   Circle with Line  4            1

lifx:
  light:
    server: 10.52.100.11

light:
  - platform: switch
    name: Livingroom Switch
    entity_id: switch.living_room_switch_switch

  - platform: group
    name: Livingroom Fixture
    entities:
      - light.livingroom_fixture_1
      - light.livingroom_fixture_2
      - light.livingroom_fixture_3

  - platform: group
    name: Livingroom
    entities:
      - light.livingroom_switch
      - light.livingroom_fixture
      - light.livingroom_entry_table

  - platform: group
    name: Bedroom
    entities:
      - light.bedroom_1
      - light.bedroom_2

  - platform: group
    name: Basement
    entities:
      - light.basement_dimmer_switch_level
      - light.basement_lamp_dimmer_plug_level

  - platform: switch
    name: Office
    entity_id: switch.office_plug_instance_1_switch

  - platform: group
    name: All Lights
    entities:
      - light.livingroom
      - light.kitchen
      - light.basement
      - light.office
      - light.bedroom


#circadian_lighting:
#  min_colortemp: 2000
#  max_colortemp: 2700
#
#switch:
#  - platform: circadian_lighting
#    name: bedroom
#    lights_ct:
#      - light.bedroom
#    disable_brightness_adjust: True
#  - platform: circadian_lighting
#    name: livingroom
#    lights_ct:
#      - light.livingroom
#    disable_brightness_adjust: True

switch:
  - platform: flux
    name: Bedroom Flux
    lights:
      - light.bedroom
    start_time: '7:00'
    stop_time: '22:00'
    start_colortemp: 2700
    stop_colortemp: 2200
    sunset_colortemp: 2500
    mode: mired
    transition: 1
    interval: 120
    disable_brightness_adjust: True
  - platform: flux
    name: Livingroom Flux
    lights:
      - light.livingroom
    start_time: '7:00'
    stop_time: '22:00'
    start_colortemp: 2700
    stop_colortemp: 2000
    sunset_colortemp: 2200
    mode: mired
    transition: 1
    interval: 120
    disable_brightness_adjust: True

automation:
  - alias: "Livingroom lights on"
    initial_state: true
    trigger:
      platform: event
      event_type: ozw.scene_activated
      event_data:
        node_id: 3
        scene_id: 2 # up
        scene_value_label: "Pressed 1 Time"
    action:
      - service: switch.turn_on
        entity_id: switch.livingroom_flux
      - service: light.turn_on
        data:
          entity_id: light.livingroom
          brightness_pct: 60
          transition: 1

  - alias: "Livingroom lights off"
    initial_state: true
    trigger:
      platform: event
      event_type: ozw.scene_activated
      event_data:
        node_id: 3
        scene_id: 1 # down
        scene_value_label: "Pressed 1 Time"
    action:
      service: light.turn_off
      entity_id: light.livingroom

  - alias: "Livingroom lights bright"
    initial_state: true
    trigger:
      platform: event
      event_type: ozw.scene_activated
      event_data:
        node_id: 3
        scene_id: 2 # up
        scene_value_label: "Pressed 2 Times"
    action:
      - service: switch.turn_off
        entity_id: switch.livingroom_flux
      - service: light.turn_on
        data:
          entity_id: light.livingroom
          brightness_pct: 100
          transition: 1

  - alias: "Livingroom lights dim"
    initial_state: true
    trigger:
      platform: event
      event_type: ozw.scene_activated
      event_data:
        node_id: 3
        scene_id: 1 # down
        scene_value_label: "Pressed 2 Times"
    action:
      - service: switch.turn_off
        entity_id: switch.livingroom_flux
      - service: light.turn_on
        data:
          entity_id: light.livingroom
          brightness_pct: 30
          transition: 1

  - alias: "All lights on"
    initial_state: true
    trigger:
      # Bedroom button 0
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 14
          scene_id: 3 # center
          scene_value_label: "Key Held down"
      # Bedroom button 1
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 15
          scene_id: 3 # center
          scene_value_label: "Key Held down"
    action:
      - service: light.turn_on
        entity_id: light.all_lights

  - alias: "All lights off"
    initial_state: true
    trigger:
      # Bedroom button 0
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 14
          scene_id: 1 # moon
          scene_value_label: "Pressed 1 Time"
      # Bedroom button 1
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 15
          scene_id: 1 # moon
          scene_value_label: "Pressed 1 Time"
    action:
      - service: light.turn_off
        entity_id: light.all_lights

  - alias: "Bedroom lights toggle"
    initial_state: true
    trigger:
      # Bedroom button 0
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 14
          scene_id: 3 # center
          scene_value_label: "Pressed 1 Time"
      # Bedroom button 1
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 15
          scene_id: 3 # center
          scene_value_label: "Pressed 1 Time"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.bedroom
                state: "on"
            sequence:
              - service: light.turn_off
                entity_id: light.bedroom
          - conditions:
              - condition: state
                entity_id: light.bedroom
                state: "off"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.bedroom
                  brightness_pct: 70
                  transition: 0.5
              - service: switch.turn_on
                entity_id: switch.bedroom_flux

  - alias: "Bedroom lights on"
    initial_state: true
    trigger:
      # Wall switch
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 6
          scene_id: 2 # up
          scene_value_label: "Pressed 1 Time"
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom
          brightness_pct: 70
          transition: 0.5
      - service: switch.turn_on
        entity_id: switch.bedroom_flux

  - alias: "Bedroom lights bright"
    initial_state: true
    trigger:
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 6
          scene_id: 2 # up
          scene_value_label: "Pressed 2 Times"
      # Bedroom button 0
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 14
          scene_id: 2 # people
          scene_value_label: "Pressed 1 Time"
      # Bedroom button 1
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 15
          scene_id: 2 # people
          scene_value_label: "Pressed 1 Time"
    action:
      - service: switch.turn_off
        entity_id: switch.bedroom_flux
      - service: light.turn_on
        data:
          entity_id: light.bedroom
          brightness_pct: 100
          transition: 0.5
          kelvin: 2700

  - alias: "Bedroom lights dim"
    initial_state: true
    trigger:
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 6
          scene_id: 1 # down
          scene_value_label: "Pressed 2 Times"
      # Bedroom button 0
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 14
          scene_id: 4 # circle-line
          scene_value_label: "Pressed 1 Time"
      # Bedroom button 1
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 15
          scene_id: 4 # circle-line
          scene_value_label: "Pressed 1 Time"
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom
          brightness_pct: 10
          transition: 0.5
          #kelvin: 1800
      - service: switch.turn_on
        entity_id: switch.bedroom_flux

  - alias: "Bedroom lights off"
    initial_state: true
    trigger:
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          node_id: 6
          scene_id: 1 # down
          scene_value_label: "Pressed 1 Time"
    action:
      service: light.turn_off
      entity_id: light.bedroom

  - alias: "Office lights on"
    initial_state: true
    trigger:
      platform: event
      event_type: ozw.scene_activated
      event_data:
        node_id: 7
        scene_id: 2 # up
        scene_value_label: "Pressed 1 Time"
    action:
      service: light.turn_on
      entity_id: light.office

  - alias: "Office lights off"
    initial_state: true
    trigger:
      platform: event
      event_type: ozw.scene_activated
      event_data:
        node_id: 7
        scene_id: 1 # down
        scene_value_id: 0 # tap
        scene_value_label: "Pressed 1 Time"
    action:
      service: light.turn_off
      entity_id: light.office

  - alias: "Basement lights off"
    initial_state: true
    trigger:
      platform: event
      event_type: ozw.scene_activated
      event_data:
        node_id: 2
        scene_id: 1 # down
        scene_value_label: "Pressed 1 Time"
    action:
      service: light.turn_off
      entity_id: light.basement

  - alias: "Basement lights on"
    initial_state: true
    trigger:
      platform: event
      event_type: ozw.scene_activated
      event_data:
        node_id: 2
        scene_id: 2 # up
        scene_value_label: "Pressed 1 Time"
    action:
      - service: light.turn_on
        entity_id: light.basement
        data:
          brightness_pct: 100

  - alias: "Basement light brightness"
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.basement_dimmer_switch_level
    condition:
      - condition: numeric_state
        entity_id: light.basement_dimmer_switch_level
        value_template: "{{ state_attr('light.basement_dimmer_switch_level', 'brightness') | int }}"
        above: 20
    action:
      - service: light.turn_on
        entity_id: light.basement_lamp_dimmer_plug_level
        data_template:
          brightness: "{{ state_attr('light.basement_dimmer_switch_level', 'brightness') | int }}"

  - alias: "Turn on front door light"
    initial_state: true
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: light.turn_on
        entity_id: light.front_door_dimmer_switch_level

  - alias: "Turn off front door light"
    initial_state: true
    trigger:
      - platform: sun
        event: sunrise
    action:
      - service: light.turn_off
        entity_id: light.front_door_dimmer_switch_level

  - alias: "Bathroom light dim start"
    initial_state: true
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: ozw.set_config_parameter
        data:
          node_id: 30  # bathroom
          parameter: 18  # "Custom Brightness Level On"
          value: 15  # percentage

  - alias: "Bathroom light dim end"
    initial_state: true
    trigger:
      - platform: time
        at: "00:06:00"
    action:
      - service: ozw.set_config_parameter
        data:
          node_id: 30  # bathroom
          parameter: 18  # "Custom Brightness Level On"
          value: 99  # percentage
